---
name: Gloat presentation
description: Gloat - the best darn presentation tool
author: Ash McKenzie
date: 2012-11-13
decks:
  -
    slug: operations-at-hooroo
    name: Operationst at Hooroo
    theme: round
    slides:
      - operations_at_hooroo.md
  -
    slug: operations-at-hooroo-ng
    name: Operationst at Hooroo NG
    theme: dark-linen
    slides:
      - operations_at_hooroo_ng.md
