---
decks:
  -
    name: Operations at Hooroo
    description: How we do operations at Hooroo
    author: Ash McKenzie
    slug: operations-at-hooroo
    theme: hooroo
    slides:
      - operations_at_hooroo.md
  -
    name: Operations at Hooroo NG
    author: Ash McKenzie
    slug: operations-at-hooroo-ng
    slides:
      - operations_at_hooroo_ng.md
