---
name: Gloat presentation
description: Gloat - the best darn presentation tool
author: Ash McKenzie
date: 2012-11-13
decks:
  -
    slug: operations-at-hooroo
    name: Operations at Hooroo
    theme: hooroo
    slides:
      - operations_at_hooroo.md
  -
    slug: operations-at-hooroo-ng
    name: Operations at Hooroo NG
    slides:
      - operations_at_hooroo_ng.md
