---
name: Gloat presentation
description: Gloat - the best darn presentation tool
author: Ash McKenzie
date: 2012-11-13
decks:
  -
    slug: operations-at-hooroo
    name: Operationst at Hooroo
    theme: hooroo
    slides:
      - operations_at_hooroo.md
